/**
 * Reference data for every Pal: display name, elements, base stats and icon.
 *
 * Generated by scripts/build-paldex.mjs from the community-extracted game
 * tables and committed, so nothing is fetched at runtime.
 */
import fs from 'fs';
import path from 'path';

export interface PalDexEntry {
  name: string;
  tribe: string;
  dex: number;
  elements: string[];
  rarity: number;
  boss: boolean;
  raid: boolean;
  nocturnal: boolean;
  /** Icon file under the UI's /pals/ directory, without the extension. */
  icon: string | null;
  hp: number;
  attack: number;
  defense: number;
  work: Record<string, number>;
}

// Read at startup rather than imported, so the compiler does not infer a type
// for 99KB of literal data. The relative path holds for both dist/lib -> dist
// and src/lib -> src, so dev and packaged builds resolve the same way.
function load(): Record<string, PalDexEntry> {
  try {
    return JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'data', 'paldex.json'), 'utf8'));
  } catch {
    // Names and icons degrade to raw ids rather than taking the panel down.
    return {};
  }
}

export const PALDEX: Record<string, PalDexEntry> = load();

/**
 * The save and the game's own data tables disagree about capitalisation
 * ("SheepBall" versus "Sheepball"), so lookups are case-insensitive.
 */
const BY_LOWER = new Map<string, PalDexEntry>();
for (const [id, entry] of Object.entries(PALDEX)) BY_LOWER.set(id.toLowerCase(), entry);

export function palEntry(characterId: string): PalDexEntry | null {
  return BY_LOWER.get(characterId.toLowerCase()) ?? null;
}

/**
 * Display name for a save's CharacterID, falling back to the raw id so an
 * unrecognised Pal from a game update still shows something meaningful.
 */
export function palName(characterId: string): string {
  const direct = palEntry(characterId);
  if (direct) return direct.boss ? `Alpha ${direct.name}` : direct.name;

  // Alphas appear as BOSS_<species> and share the base species' entry.
  const base = characterId.replace(/^BOSS_/i, '');
  const entry = palEntry(base);
  if (entry) return base === characterId ? entry.name : `Alpha ${entry.name}`;

  return characterId;
}
